version: '2.15.1'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todo_django
    volumes:
      - .:/todo_django
    ports:
      - "8000:8000"